[package]
name = "symspell"
version = "0.1.0"
license = "MIT"
authors = ["Rene Klacan <rene.klacan@gmail.com>"]
keywords = ["spellcheck"]
description = "Spelling correction & Fuzzy search"
homepage = "https://github.com/reneklacan/symspell-rs"
repository = "https://github.com/reneklacan/symspell-rs"

[dependencies]
strsim = "^0.7"
unidecode = "^0.3"
derive_builder = "^0.5"

[[example]]
name = "demo"